"""Contrainte unique sur favoris (user_id, type_favoris, item_id)

Revision ID: 0b469cd4258e
Revises: 3b77e274b42c
Create Date: 2026-07-09 10:15:18.686851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b469cd4258e'
down_revision: Union[str, Sequence[str], None] = '3b77e274b42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_favoris_user_type_item', 'favoris', ['user_id', 'type_favoris', 'item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_favoris_user_type_item', 'favoris', type_='unique')
    # ### end Alembic commands ###
