"""ajout identifiant, email optionnel

Revision ID: 19050635251a
Revises: 3225db66213a
Create Date: 2026-07-08 09:59:50.679248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19050635251a'
down_revision: Union[str, Sequence[str], None] = '3225db66213a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identifiant', sa.String(length=100), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['identifiant'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('users', 'identifiant')
    # ### end Alembic commands ###
