"""lecteurs multiples par lecture

Revision ID: 3225db66213a
Revises: ef65506b0f99
Create Date: 2026-07-01 12:53:21.476413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3225db66213a'
down_revision: Union[str, Sequence[str], None] = 'ef65506b0f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_lecteurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('lecteur_id', sa.Integer(), nullable=False),
    sa.Column('langue', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lecteur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lecture_id'], ['lecture_biblique.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_lecteurs_id'), 'lecture_lecteurs', ['id'], unique=False)
    op.drop_constraint(op.f('lecture_biblique_lecteur_id_fkey'), 'lecture_biblique', type_='foreignkey')
    op.drop_column('lecture_biblique', 'lecteur_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_biblique', sa.Column('lecteur_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('lecture_biblique_lecteur_id_fkey'), 'lecture_biblique', 'users', ['lecteur_id'], ['id'])
    op.drop_index(op.f('ix_lecture_lecteurs_id'), table_name='lecture_lecteurs')
    op.drop_table('lecture_lecteurs')
    # ### end Alembic commands ###
