"""renomme url_audio en fichier_audio_url

Revision ID: 3b77e274b42c
Revises: 19050635251a
Create Date: 2026-07-08 11:12:53.885349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b77e274b42c'
down_revision: Union[str, Sequence[str], None] = '19050635251a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chants', sa.Column('fichier_audio_url', sa.String(length=255), nullable=True))
    op.drop_column('chants', 'url_audio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chants', sa.Column('url_audio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('chants', 'fichier_audio_url')
    # ### end Alembic commands ###
