"""initial tables

Revision ID: ef65506b0f99
Revises: 
Create Date: 2026-07-01 11:27:24.528173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef65506b0f99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('paroles', sa.Text(), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('categorie', sa.Enum('CHANT', 'CHANT_DE_MESSE', 'CHANT_DE_LA_SAINTETE', 'CHANT_DE_LA_VIE', 'CHANT_DE_LA_PAIX', 'CHANT_DE_LA_JOIE', name='categoriechantenum', native_enum=False), nullable=False),
    sa.Column('auteur', sa.String(length=255), nullable=True),
    sa.Column('url_audio', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_chants_id'), 'chants', ['id'], unique=False)
    op.create_table('paroisses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('pasteur_nom', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paroisses_id'), 'paroisses', ['id'], unique=False)
    op.create_table('evenements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('paroisse_id', sa.Integer(), nullable=False),
    sa.Column('lieu', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('publie', sa.Boolean(), nullable=True),
    sa.Column('type_evenement', sa.Enum('CONFERENCE', 'SEMAINE_DE_LA_JEUNESSE', 'SEMAINE_DES_FEMMES', 'FORMATION', 'CONCERT', 'EVANGELISATION', name='evenementtypeenum', native_enum=False), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paroisse_id'], ['paroisses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evenements_id'), 'evenements', ['id'], unique=False)
    op.create_table('medias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('type_media', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', name='mediatypeenum', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url_media', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('duree_secondes', sa.Integer(), nullable=True),
    sa.Column('paroisse_id', sa.Integer(), nullable=False),
    sa.Column('publie', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paroisse_id'], ['paroisses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medias_id'), 'medias', ['id'], unique=False)
    op.create_table('programme_culte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('type_culte', sa.Enum('ACTION_DE_GRACE', 'DIMANCHE', 'MERCREDI', 'VENDREDI', 'ANIVERSAIRE', 'PAQUES', 'PENTECOTE', 'NOEL', 'REVEILLON', 'REVEILLON_DE_NOEL', name='cultetypeenum', native_enum=False), nullable=False),
    sa.Column('predicateur', sa.String(length=255), nullable=True),
    sa.Column('date_heure', sa.TIMESTAMP(), nullable=False),
    sa.Column('paroisse_id', sa.Integer(), nullable=False),
    sa.Column('publie', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paroisse_id'], ['paroisses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programme_culte_id'), 'programme_culte', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin_paroisse', 'resp_musical', 'resp_lecteurs', 'fidele', name='roleenum', native_enum=False), nullable=False),
    sa.Column('paroisse_id', sa.Integer(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paroisse_id'], ['paroisses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('annonces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('type_annonce', sa.Enum('MARRIAGE', 'FUNERAIRE', 'BAPTEME', 'CONFIRMATION', 'REUNION', 'ASSEMBLEE', name='annoncetype', native_enum=False), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('paroisse_id', sa.Integer(), nullable=False),
    sa.Column('publie', sa.Boolean(), nullable=True),
    sa.Column('important', sa.Boolean(), nullable=True),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paroisse_id'], ['paroisses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annonces_id'), 'annonces', ['id'], unique=False)
    op.create_table('favoris',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_favoris', sa.Enum('ANNONCE', 'EVENEMENT', 'MEDIA', 'CHANT', 'ARTICLE', name='favoristypeenum', native_enum=False), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favoris_id'), 'favoris', ['id'], unique=False)
    op.create_table('lecture_biblique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('texte', sa.Text(), nullable=True),
    sa.Column('date_lecture', sa.TIMESTAMP(), nullable=False),
    sa.Column('type_evenement', sa.String(length=100), nullable=True),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('lecteur_id', sa.Integer(), nullable=False),
    sa.Column('paroisse_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lecteur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paroisse_id'], ['paroisses.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programme_culte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_biblique_id'), 'lecture_biblique', ['id'], unique=False)
    op.create_table('programme_chants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_culte_id', sa.Integer(), nullable=False),
    sa.Column('chant_id', sa.Integer(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chant_id'], ['chants.id'], ),
    sa.ForeignKeyConstraint(['programme_culte_id'], ['programme_culte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programme_chants_id'), 'programme_chants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programme_chants_id'), table_name='programme_chants')
    op.drop_table('programme_chants')
    op.drop_index(op.f('ix_lecture_biblique_id'), table_name='lecture_biblique')
    op.drop_table('lecture_biblique')
    op.drop_index(op.f('ix_favoris_id'), table_name='favoris')
    op.drop_table('favoris')
    op.drop_index(op.f('ix_annonces_id'), table_name='annonces')
    op.drop_table('annonces')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_programme_culte_id'), table_name='programme_culte')
    op.drop_table('programme_culte')
    op.drop_index(op.f('ix_medias_id'), table_name='medias')
    op.drop_table('medias')
    op.drop_index(op.f('ix_evenements_id'), table_name='evenements')
    op.drop_table('evenements')
    op.drop_index(op.f('ix_paroisses_id'), table_name='paroisses')
    op.drop_table('paroisses')
    op.drop_index(op.f('ix_chants_id'), table_name='chants')
    op.drop_table('chants')
    # ### end Alembic commands ###
